server:
  port: 8080
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:mysql://172.29.50.141:3306/proj_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: appuser
    password: RuanGongDemo!123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Shanghai

  mvc:
    dispatch-options-requests: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.szu.admin.domain