server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: Eyja_Sakura
    password: 051211JYBCMX..
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.admin.domain